// Mocks generated by Mockito 5.4.6 from annotations
// in smart_resources/test/integration_test/integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_resources/core/network/network_service.dart' as _i6;
import 'package:smart_resources/features/auth/data/models/user_model.dart'
    as _i2;
import 'package:smart_resources/features/home/domain/entities/activity.dart'
    as _i8;
import 'package:smart_resources/features/requests/data/models/request_model.dart'
    as _i5;
import 'package:smart_resources/features/resources/data/models/resource_model.dart'
    as _i3;
import 'package:smart_resources/features/resources/data/models/review_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResourceModel_1 extends _i1.SmartFake implements _i3.ResourceModel {
  _FakeResourceModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReviewModel_2 extends _i1.SmartFake implements _i4.ReviewModel {
  _FakeReviewModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequestModel_3 extends _i1.SmartFake implements _i5.RequestModel {
  _FakeRequestModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i6.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.UserModel?> authenticate(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [email, password]),
            returnValue: _i7.Future<_i2.UserModel?>.value(),
          )
          as _i7.Future<_i2.UserModel?>);

  @override
  _i7.Future<_i2.UserModel> register(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#register, [user]),
            returnValue: _i7.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#register, [user])),
            ),
          )
          as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<List<_i2.UserModel>> fetchUsers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, []),
            returnValue: _i7.Future<List<_i2.UserModel>>.value(
              <_i2.UserModel>[],
            ),
          )
          as _i7.Future<List<_i2.UserModel>>);

  @override
  _i7.Future<void> updateUser(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.ResourceModel>> fetchResources() =>
      (super.noSuchMethod(
            Invocation.method(#fetchResources, []),
            returnValue: _i7.Future<List<_i3.ResourceModel>>.value(
              <_i3.ResourceModel>[],
            ),
          )
          as _i7.Future<List<_i3.ResourceModel>>);

  @override
  _i7.Future<_i3.ResourceModel?> fetchResourceById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchResourceById, [id]),
            returnValue: _i7.Future<_i3.ResourceModel?>.value(),
          )
          as _i7.Future<_i3.ResourceModel?>);

  @override
  _i7.Future<_i3.ResourceModel> uploadResource(_i3.ResourceModel? resource) =>
      (super.noSuchMethod(
            Invocation.method(#uploadResource, [resource]),
            returnValue: _i7.Future<_i3.ResourceModel>.value(
              _FakeResourceModel_1(
                this,
                Invocation.method(#uploadResource, [resource]),
              ),
            ),
          )
          as _i7.Future<_i3.ResourceModel>);

  @override
  _i7.Future<void> updateResource(_i3.ResourceModel? resource) =>
      (super.noSuchMethod(
            Invocation.method(#updateResource, [resource]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> approveResource(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#approveResource, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteResource(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteResource, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.ResourceModel>> fetchBookmarks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBookmarks, [userId]),
            returnValue: _i7.Future<List<_i3.ResourceModel>>.value(
              <_i3.ResourceModel>[],
            ),
          )
          as _i7.Future<List<_i3.ResourceModel>>);

  @override
  _i7.Future<void> addBookmark(String? userId, String? resourceId) =>
      (super.noSuchMethod(
            Invocation.method(#addBookmark, [userId, resourceId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeBookmark(String? userId, String? resourceId) =>
      (super.noSuchMethod(
            Invocation.method(#removeBookmark, [userId, resourceId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.ReviewModel>> fetchReviews(String? resourceId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchReviews, [resourceId]),
            returnValue: _i7.Future<List<_i4.ReviewModel>>.value(
              <_i4.ReviewModel>[],
            ),
          )
          as _i7.Future<List<_i4.ReviewModel>>);

  @override
  _i7.Future<_i4.ReviewModel> addReview(_i4.ReviewModel? review) =>
      (super.noSuchMethod(
            Invocation.method(#addReview, [review]),
            returnValue: _i7.Future<_i4.ReviewModel>.value(
              _FakeReviewModel_2(this, Invocation.method(#addReview, [review])),
            ),
          )
          as _i7.Future<_i4.ReviewModel>);

  @override
  _i7.Future<List<_i5.RequestModel>> fetchRequests() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRequests, []),
            returnValue: _i7.Future<List<_i5.RequestModel>>.value(
              <_i5.RequestModel>[],
            ),
          )
          as _i7.Future<List<_i5.RequestModel>>);

  @override
  _i7.Future<_i5.RequestModel> createRequest(_i5.RequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#createRequest, [request]),
            returnValue: _i7.Future<_i5.RequestModel>.value(
              _FakeRequestModel_3(
                this,
                Invocation.method(#createRequest, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.RequestModel>);

  @override
  _i7.Future<void> updateRequest(_i5.RequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateRequest, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.RequestModel?> fulfillRequest(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fulfillRequest, [id]),
            returnValue: _i7.Future<_i5.RequestModel?>.value(),
          )
          as _i7.Future<_i5.RequestModel?>);

  @override
  _i7.Future<void> deleteRequest(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRequest, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.Activity>> fetchActivities({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActivities, [], {#userId: userId}),
            returnValue: _i7.Future<List<_i8.Activity>>.value(<_i8.Activity>[]),
          )
          as _i7.Future<List<_i8.Activity>>);

  @override
  _i7.Future<void> logActivity(_i8.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#logActivity, [activity]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
